{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gitlab-workspaces-proxy.fullname" . -}}
{{- $svcPort := .Values.service.http.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gitlab-workspaces-proxy.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.host.workspaceDomain | quote }}
      secretName: {{ include "gitlab-workspaces-proxy.fullname" . }}-workspaces-cert
    - hosts:
      - {{ .Values.ingress.host.wildcardDomain | quote }}
      secretName:  {{ include "gitlab-workspaces-proxy.fullname" . }}-workspaces-wildcard-cert
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host.workspaceDomain | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  {{ include "gitlab-workspaces-proxy.fullname" . }}-http
            port:
              number: {{ $svcPort }}
  - host: {{ .Values.ingress.host.wildcardDomain | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  {{ include "gitlab-workspaces-proxy.fullname" . }}-http
            port:
              number: {{ $svcPort }}
{{- end }}
