apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gitlab-workspaces-proxy.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gitlab-workspaces-proxy.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "gitlab-workspaces-proxy.serviceAccountName" . }}
  namespace: gitlab-workspaces
roleRef:
  name: {{ include "gitlab-workspaces-proxy.fullname" . }}
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
