apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-workspaces-proxy.fullname" . }}
  labels:
    {{- include "gitlab-workspaces-proxy.labels" . | nindent 4 }}
type: "generic"
stringData:
  config.yaml: |
    {{- with .Values.auth }}
    auth:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    port: {{ .Values.port }}
    metrics_path: {{ .Values.metrics_path }}
    log_level: {{ .Values.log_level }}
---
{{- if .Values.ingress.tls.workspaceDomainKey }}
apiVersion: v1
data:
  tls.crt: {{ .Values.ingress.tls.workspaceDomainCert |  b64enc }}
  tls.key:  {{ .Values.ingress.tls.workspaceDomainKey |  b64enc }}
kind: Secret
metadata:
  name: {{ include "gitlab-workspaces-proxy.fullname" . }}-workspaces-cert
type: kubernetes.io/tls
{{ end }}
---
{{- if .Values.ingress.tls.wildcardDomainKey }}
apiVersion: v1
data:
  tls.crt: {{ .Values.ingress.tls.wildcardDomainCert |  b64enc }}
  tls.key: {{ .Values.ingress.tls.wildcardDomainKey |  b64enc }}
kind: Secret
metadata:
  name: {{ include "gitlab-workspaces-proxy.fullname" . }}-workspaces-wildcard-cert
type: kubernetes.io/tls
{{ end }}
