apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-workspaces-proxy.fullname" . }}
  labels:
    {{- include "gitlab-workspaces-proxy.labels" . | nindent 4 }}
type: "generic"
stringData:
  config.yaml: |
    {{- with .Values.auth }}
    auth:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    port: {{ .Values.port }}
    metrics_path: {{ .Values.metrics_path }}
