apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab-workspaces-proxy.fullname" . }}
  labels:
    {{- include "gitlab-workspaces-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    {{- include "gitlab-workspaces-proxy.selectorLabels" . | nindent 4 }}
